// ---------------------------------------------------------------------------
// Gerber (RS-274X) + Excellon export for real PCB fabrication.
//
// Volt's own CAM pipeline (pcbExporter.ts) ends at G-code, streamed straight
// to a CNC over WebSerial. That's a mill-it-yourself path; most boards go to
// a fab house instead (JLCPCB, PCBWay, OSHPark, ...), which read the same two
// ancient, boring formats every PCB tool speaks: RS-274X for copper/outline
// layers, and Excellon for drill hits.
//
// Reuses `PcbLayoutResult.copperByNet` (populated in pcbExporter.ts as a side
// effect of the flood-fill stage that already runs for the SVG preview and the
// isolation toolpaths) rather than re-deriving copper from traces/pads here —
// two independent flood-fill implementations would drift, and the whole point
// of a Gerber export is that it matches what the mill would actually cut.
// ---------------------------------------------------------------------------

import JSZip from 'jszip';
import type { PcbLayoutResult, DrillPoint, BoardCutout } from './pcbExporter';
import type { Poly } from './pcbGeometry';

/** Gerber fixed-point format: 3 integer + 4 fractional digits (0.1um steps). */
const COORD_SCALE = 1e4;

function formatCoord(mm: number): string {
  return String(Math.round(mm * COORD_SCALE));
}

/** Excellon wants zero-padded fixed-width coordinates, no decimal point. */
function formatExcellonCoord(mm: number): string {
  const negative = mm < 0;
  const units = Math.round(Math.abs(mm) * COORD_SCALE);
  return (negative ? '-' : '') + String(units).padStart(7, '0');
}

function gerberHeader(layerFunction: string): string {
  return (
    '%FSLAX34Y34*%\n' +
    '%MOMM*%\n' +
    '%LPD*%\n' +
    'G04 Generated by PhysBox Volt*\n' +
    '%TF.GenerationSoftware,PhysBox,Volt,1.0*%\n' +
    `%TF.FileFunction,${layerFunction}*%\n`
  );
}

function appendRegion(lines: string[], ring: Poly): void {
  if (ring.length < 3) return;
  lines.push('G36*');
  lines.push(`X${formatCoord(ring[0].x)}Y${formatCoord(ring[0].y)}D02*`);
  for (let i = 1; i < ring.length; i++) {
    lines.push(`X${formatCoord(ring[i].x)}Y${formatCoord(ring[i].y)}D01*`);
  }
  lines.push(`X${formatCoord(ring[0].x)}Y${formatCoord(ring[0].y)}D01*`);
  lines.push('G37*');
}

function generateCopperLayer(copperByNet: Map<string, Poly[]>, layerFunction: string): string {
  const lines: string[] = [gerberHeader(layerFunction), '%ADD10C,0.1*%', 'D10*'];
  for (const polys of copperByNet.values()) {
    for (const ring of polys) appendRegion(lines, ring);
  }
  lines.push('M02*');
  return lines.join('\n') + '\n';
}

function generateOutlineLayer(
  boardWidthMm: number,
  boardHeightMm: number,
  boardOriginMm: number,
  cutouts: BoardCutout[]
): string {
  const lines: string[] = [gerberHeader('Profile,NP'), '%ADD11C,0.1*%', 'D11*'];

  const strokeClosedPath = (pts: { x: number; y: number }[]) => {
    if (pts.length < 2) return;
    lines.push(`X${formatCoord(pts[0].x)}Y${formatCoord(pts[0].y)}D02*`);
    for (let i = 1; i < pts.length; i++) {
      lines.push(`X${formatCoord(pts[i].x)}Y${formatCoord(pts[i].y)}D01*`);
    }
    lines.push(`X${formatCoord(pts[0].x)}Y${formatCoord(pts[0].y)}D01*`);
  };

  const x0 = boardOriginMm;
  const y0 = boardOriginMm;
  strokeClosedPath([
    { x: x0, y: y0 },
    { x: x0 + boardWidthMm, y: y0 },
    { x: x0 + boardWidthMm, y: y0 + boardHeightMm },
    { x: x0, y: y0 + boardHeightMm },
  ]);

  // Interior cutouts (e.g. mounting slots) as their own closed rectangles —
  // milled through-board, so on the outline layer rather than copper.
  for (const cutout of cutouts) {
    if (cutout.shape !== 'rect') continue;
    const hw = cutout.widthMm / 2;
    const hh = cutout.heightMm / 2;
    strokeClosedPath([
      { x: cutout.x - hw, y: cutout.y - hh },
      { x: cutout.x + hw, y: cutout.y - hh },
      { x: cutout.x + hw, y: cutout.y + hh },
      { x: cutout.x - hw, y: cutout.y + hh },
    ]);
  }

  lines.push('M02*');
  return lines.join('\n') + '\n';
}

function generateExcellonDrill(drills: DrillPoint[]): { text: string; drillCount: number } {
  // One tool per distinct diameter, rounded to the micron.
  const toolDiameterByKey = new Map<number, number>();
  for (const d of drills) {
    const key = Math.round(d.diameter * 1000);
    toolDiameterByKey.set(key, d.diameter);
  }
  const sortedKeys = [...toolDiameterByKey.keys()].sort((a, b) => a - b);
  const toolNumberByKey = new Map<number, number>();
  sortedKeys.forEach((key, i) => toolNumberByKey.set(key, i + 1));

  const lines: string[] = ['M48', 'METRIC,LZ'];
  for (const key of sortedKeys) {
    const toolNum = String(toolNumberByKey.get(key)).padStart(2, '0');
    lines.push(`T${toolNum}C${toolDiameterByKey.get(key)!.toFixed(3)}`);
  }
  lines.push('%', 'G90', 'G05');

  let drillCount = 0;
  for (const key of sortedKeys) {
    const toolNum = String(toolNumberByKey.get(key)).padStart(2, '0');
    lines.push(`T${toolNum}`);
    for (const d of drills) {
      if (Math.round(d.diameter * 1000) !== key) continue;
      lines.push(`X${formatExcellonCoord(d.x)}Y${formatExcellonCoord(d.y)}`);
      drillCount++;
    }
  }
  lines.push('M30');
  return { text: lines.join('\n') + '\n', drillCount };
}

export interface GerberExportFiles {
  [filename: string]: string;
}

/**
 * Renders a routed board to a fab-house-ready file set. Two-layer boards get
 * both copper layers; single-layer boards (the common case — see
 * {@link PcbLayoutResult.layers}) get just the top.
 */
export function generateGerberFiles(result: PcbLayoutResult): GerberExportFiles {
  const files: GerberExportFiles = {};

  files['board-F_Cu.gtl'] = generateCopperLayer(result.copperByNet, 'Copper,L1,Top');
  if (result.layers === 2 && result.bottomCopperByNet) {
    files['board-B_Cu.gbl'] = generateCopperLayer(result.bottomCopperByNet, 'Copper,L2,Bot');
  }
  files['board-Edge_Cuts.gko'] = generateOutlineLayer(
    result.boardWidthMm,
    result.boardHeightMm,
    result.boardOriginMm,
    result.cutouts
  );
  const drill = generateExcellonDrill(result.drills.filter(d => d.diameter > 0));
  files['board.drl'] = drill.text;

  return files;
}

/** Bundles the Gerber/Excellon file set into a single downloadable zip. */
export async function generateGerberZip(result: PcbLayoutResult): Promise<Blob> {
  const files = generateGerberFiles(result);
  const zip = new JSZip();
  for (const [name, contents] of Object.entries(files)) {
    zip.file(name, contents);
  }
  return zip.generateAsync({ type: 'blob' });
}
